version: '3.7'

services:
 cuurency-exchange:
  image: sudipcold/ms-currency-exchange-microservice:0.0.1-SNAPSHOT
  mem_limit: 700m
  ports:
   - "8000:8000"
  networks:
   - currency-network
  depends_on:
   - naming-server
   - rabbitmq
  environment:
   EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
   SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
   RABBIT_URI: amqp://guest:guest@rabbitmq:5672
   SPRING_RABBITMQ_HOST: rabbitmq
   SPRING_ZIPKIN_SENDER_TYPE: rabbit

 naming-server:
  image: sudipcold/ms-naming-server:0.0.1-SNAPSHOT
  mem_limit: 700m
  ports:
   - "8761:8761"
  networks:
   - currency-network

 currency-conversion:
  image: sudipcold/ms-currency-conversion-microservice:0.0.1-SNAPSHOT
  mem_limit: 700m
  ports:
   - "8100:8100"
  networks:
   - currency-network
  depends_on:
   - naming-server
   - rabbitmq
  environment:
   EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
   SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
   RABBIT_URI: amqp://guest:guest@rabbitmq:5672
   SPRING_RABBITMQ_HOST: rabbitmq
   SPRING_ZIPKIN_SENDER_TYPE: rabbit

 api-gateway:
  image: sudipcold/ms-api-gateway:0.0.1-SNAPSHOT
  mem_limit: 700m
  ports:
   - "8765:8765"
  networks:
   - currency-network
  depends_on:
   - naming-server
   - rabbitmq
  environment:
   EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
   SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
   RABBIT_URI: amqp://guest:guest@rabbitmq:5672
   SPRING_RABBITMQ_HOST: rabbitmq
   SPRING_ZIPKIN_SENDER_TYPE: rabbit

 zipkin-server:
  image: openzipkin/zipkin:latest
  ports:
   - "9411:9411"
  networks:
   - currency-network
  mem_limit: 300m
  environment:
   RABBIT_URI: amqp://guest:guest@rabbitmq:5672
  depends_on:
   - rabbitmq

 rabbitmq:
  image: rabbitmq:latest
  ports:
   - "5672:5672"
   - "15672:15672"
  networks:
   - currency-network
  mem_limit: 300m

networks:
  currency-network:

